import type { TestRun, TestCase } from "@/db/schema";

const now = new Date();
const hour = (h: number) => new Date(now.getTime() - h * 3600000);

export const mockRuns: TestRun[] = [
  {
    runId: 12847365,
    suite: "cmr",
    status: "passed",
    total: 24,
    passed: 24,
    failed: 0,
    flaky: 1,
    skipped: 0,
    durationMs: 182000,
    triggeredBy: "workflow_dispatch",
    commitSha: "a3f7c2e1b8d94e6f0123456789abcdef01234567",
    branch: "main",
    createdAt: hour(1),
  },
  {
    runId: 12847201,
    suite: "albumbuddy",
    status: "failed",
    total: 18,
    passed: 15,
    failed: 3,
    flaky: 0,
    skipped: 0,
    durationMs: 145000,
    triggeredBy: "push",
    commitSha: "b4e8d3f2a9c05e7f1234567890abcdef12345678",
    branch: "main",
    createdAt: hour(3),
  },
  {
    runId: 12846998,
    suite: "cmr",
    status: "passed",
    total: 24,
    passed: 24,
    failed: 0,
    flaky: 0,
    skipped: 0,
    durationMs: 175000,
    triggeredBy: "workflow_dispatch",
    commitSha: "c5f9e4a3b0d16f8a2345678901abcdef23456789",
    branch: "main",
    createdAt: hour(6),
  },
  {
    runId: 12846750,
    suite: "all",
    status: "failed",
    total: 42,
    passed: 38,
    failed: 4,
    flaky: 2,
    skipped: 0,
    durationMs: 310000,
    triggeredBy: "push",
    commitSha: "d6a0f5b4c1e27a9b3456789012abcdef34567890",
    branch: "feature/add-search",
    createdAt: hour(12),
  },
  {
    runId: 12846500,
    suite: "cmr",
    status: "passed",
    total: 24,
    passed: 24,
    failed: 0,
    flaky: 0,
    skipped: 0,
    durationMs: 168000,
    triggeredBy: "workflow_dispatch",
    commitSha: "e7b1a6c5d2f38b0c4567890123abcdef45678901",
    branch: "main",
    createdAt: hour(24),
  },
];

export const mockTestCases: TestCase[] = [
  {
    id: 1,
    runId: 12847201,
    title: "AlbumBuddy 모니터링 > 헬스체크 > AB-HC-01: 메인 페이지 로드 확인",
    file: "tests/ab_monitoring_pom.spec.ts",
    project: "albumbuddy-monitoring",
    status: "passed",
    durationMs: 3200,
    errorMessage: null,
    errorStack: null,
  },
  {
    id: 2,
    runId: 12847201,
    title: "AlbumBuddy 모니터링 > 검색 기능 > AB-SEARCH-01: 상품 검색 결과 표시",
    file: "tests/ab_monitoring_pom.spec.ts",
    project: "albumbuddy-monitoring",
    status: "passed",
    durationMs: 5400,
    errorMessage: null,
    errorStack: null,
  },
  {
    id: 3,
    runId: 12847201,
    title: "AlbumBuddy 모니터링 > 장바구니 > AB-CART-01: 장바구니 추가 동작",
    file: "tests/ab_monitoring_pom.spec.ts",
    project: "albumbuddy-monitoring",
    status: "failed",
    durationMs: 30000,
    errorMessage: "Error: locator.click: Timeout 30000ms exceeded.\nCall log:\n  - waiting for getByRole('button', { name: '장바구니 담기' })",
    errorStack: "  at AlbumBuddyPage.addToCart (tests/pages/albumbuddy.page.ts:45:18)\n  at tests/ab_monitoring_pom.spec.ts:67:5",
  },
  {
    id: 4,
    runId: 12847201,
    title: "AlbumBuddy 모니터링 > 주문 > AB-ORDER-01: 주문서 페이지 접근",
    file: "tests/ab_monitoring_pom.spec.ts",
    project: "albumbuddy-monitoring",
    status: "failed",
    durationMs: 30000,
    errorMessage: "Error: expect(received).toBeVisible()\n\nExpected: visible\nReceived: hidden\n\nCall log:\n  - expect.toBeVisible with timeout 15000ms\n  - waiting for getByText('주문서 작성')",
    errorStack: "  at tests/ab_monitoring_pom.spec.ts:89:32",
  },
  {
    id: 5,
    runId: 12847201,
    title: "AlbumBuddy 모니터링 > 결제 > AB-PAY-01: 결제 수단 선택 표시",
    file: "tests/ab_monitoring_pom.spec.ts",
    project: "albumbuddy-monitoring",
    status: "failed",
    durationMs: 30000,
    errorMessage: "Error: page.goto: net::ERR_CONNECTION_TIMED_OUT at https://albumbuddy.makestar.co/payment",
    errorStack: "  at AlbumBuddyPage.goToPayment (tests/pages/albumbuddy.page.ts:72:10)\n  at tests/ab_monitoring_pom.spec.ts:102:5",
  },
  ...Array.from({ length: 13 }, (_, i) => ({
    id: 6 + i,
    runId: 12847201,
    title: `AlbumBuddy 모니터링 > 기능${i + 1} > AB-FN-${String(i + 1).padStart(2, "0")}: 정상 동작 확인`,
    file: "tests/ab_monitoring_pom.spec.ts",
    project: "albumbuddy-monitoring",
    status: "passed" as const,
    durationMs: 2000 + Math.floor(Math.random() * 5000),
    errorMessage: null,
    errorStack: null,
  })),
];
